### ISSUE TITLE
Invalid Request Paylod when linking

### ISSUE THREAD

**Issue by Jevaan** [OldSmurf56/xpeng#1]
When I try to link the car running this command:
curl https://enode-api.production.enode.io/users/{USERID}/link -X POST ^ -H "Authorization: Bearer {ACCESS TOKEN}" ^ -H "Content-Type: application/json" ^ -d "{ "vendorType": "vehicle", "scopes": ["vehicle:read:data", "vehicle:read:location", "vehicle:control:charging"], "language": "en-US", "redirectUri": "https://localhost:3000\" }"

Returns:

{"type":"https://developers.enode.com/api/problems/bad-request","title":"Bad Request","detail":"Invalid request payload JSON format"}curl: (3) unmatched close brace/bracket in URL position 1:

**Comment by OldSmurf56** [comment]
Try pasting it without  the ^ and just have everything in one line

curl https://enode-api.production.enode.io/users/{UserID}/link -X POST -H "Authorization: Bearer {AccessToken}" -H "Content-Type: application/json" -d "{ \"vendorType\": \"vehicle\", \"scopes\": [\"vehicle:read:data\", \"vehicle:read:location\", \"vehicle:control:charging\"], \"language\": \"en-US\", \"redirectUri\": \"https://localhost:3000\" }"

and of course replace {UserID} and {AccessToken} with your values. And remember that the AccessToken expires after one hour

**Comment by OldSmurf56** [comment]
Closed since there was no issue
