### ISSUE TITLE
An error in step 4 - What am I missing?

### ISSUE THREAD

**Issue by Fannangir** [OldSmurf56/xpeng#2]
Hi,

I have received the following error in step 4:

![image](https://github.com/user-attachments/assets/b84b4f4c-1158-491e-b954-fb2799d9039c)

What am I missing?
Pretty sure that I have been using the exact format.

**Comment by Fannangir** [comment]
Tried without "^", same result.

curl [https://enode-api.production.enode.io/users/{UserID}/link](https://enode-api.production.enode.io/users/%7BUserID%7D/link) -X POST -H "Authorization: Bearer {AccessToken}" -H "Content-Type: application/json" -d "{ "vendorType": "vehicle", "scopes": ["vehicle:read:data", "vehicle:read:location", "vehicle:control:charging"], "language": "en-US", "redirectUri": "[https://localhost:3000\](https://localhost:3000%5C/)" }"

**Comment by Fannangir** [comment]
OK, found the correct curl syntax under Windows CMD, as follows (would recommend to update documentation):
curl https://enode-api.production.enode.io/users/{Client-Id}/link -H "Authorization: Bearer {Token}" --json "{ \"vendorType\": \"vehicle\", \"scopes\": [\"vehicle:read:data\", \"vehicle:read:location\", \"vehicle:control:charging\"], \"language\": \"en-US\", \"redirectUri\": \"https://localhost:3000\" }"

**Comment by OldSmurf56** [comment]
The code does work - several users have reported back with success.

Did you replace the {Token} with an updated one? Remember the token will time out after an hour, so you should always renew it before trying again,
Furthermore - did you insert your own {Client-Id} ?

**Comment by Fannangir** [comment]
Yes, sure, generated a new one after the older one has expired.

I have googled a bit regarding the syntax to be used in windows cmd, and found the syntax I have used which solved the problem.
It recommends to remove the POST, use —json if a join format is used, and add the \ before opening “ and another \ before “.

After replacement of the syntax, worked in first shot.

**Comment by frankyman88** [comment]
I was getting the same error regarding unmatched closed bracket, but unfortunately @Fannangir 's solution didnt work for me either. @stevelea from the XPENG Australia group helped me out with the following formatting which worked via CMD on Windows 11:
`curl "https://enode-api.production.enode.io/users/YOUR_CLIENT_ID/link" ^
  -X POST ^
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN" ^
  -H "Content-Type: application/json" ^
  -d "{\"vendorType\":\"vehicle\",\"scopes\":[\"vehicle:read:data\",\"vehicle:read:location\",\"vehicle:control:charging\"],\"language\":\"en-US\",\"redirectUri\":\"https://localhost:3000\"}"`
