### ISSUE TITLE
MQTT should be updated with local setting

### ISSUE THREAD

**Issue by krossingdk** [OldSmurf56/xpeng#3]
Many thanks for a great work - my Xpeng is now tracked in my HA - really great stuff

As I'm a complete beginner wirh Node Red it took me some time to figure out that the mqtt should be updated with my local settings including IP, username and password. It may be obvious for for the experienced user but just liked to mention for other newbies

**Comment by OldSmurf56** [comment]
Glad you like my work and thanks for your input.

I added a line in the Home Assistant section to remind users to updated the Node Red info.
